class Product {
  final String title, description, category;
  final List<String> images, specificationsName, specificationsInfo;
  final int price, oldPrice, count;
  final Map<String, List<String>>? options;
  final bool isRecommended, isDiscounted;

  Product({
    this.options,
    required this.images,
    required this.count,
    required this.description,
    required this.title,
    required this.category,
    required this.price,
    required this.oldPrice,
    required this.isRecommended,
    required this.specificationsName,
    required this.specificationsInfo,
    required this.isDiscounted,
  });
}

List<Product> products = [
  Product(
    options: {
      "Базовая кривизна": ['8.4', '8.8'],
      'Оптическая сила': [
        '+8',
        '+7.5',
        '+7',
        '+6.5',
        '+6',
        '+5.5',
        '+5',
        '+4.5',
        '+4',
        '+3.5',
        '+3',
        '+2.5',
        '+2',
        '+1.5',
        '+1',
        '+0.5',
        '-0.5',
        '-1',
        '-1.5',
        '-2',
        '-2.5',
        '-3',
        '-3.5',
        '-4',
        '-4.5',
        '-5',
        '-5.5',
        '-6',
        '-6.5',
        '-7',
        '-7.5',
        '-8'
      ],
    },
    count: 4,
    images: ["assets/images/product_1.png", "assets/images/product_1-1.png"],
    description:
        "AOSEPT® plus HydraGlyde® обеспечивает эффективную очистку и надежную дезинфекцию контактных линз. За счет матрицы HydraGlyde®, которая способствует длительному увлажнению, в линзах комфортно в течении всего дня. Не содержит консервантов! Подходит для чувствительных глаз!",
    title: "ACUVUE OASYS (24 шт.)",
    category: "lens",
    price: 5070,
    oldPrice: 6000,
    isRecommended: false,
    isDiscounted: true,
    specificationsName: [
      "Производитель",
      "Доступность",
      "Кислородопроницаемость"
    ],
    specificationsInfo: ["Johnson&Johnson", "На складе", "147"],
  ),
  Product(
    count: 10,
    images: ["assets/images/product_2.png"],
    description:
        "AOSEPT® plus HydraGlyde® обеспечивает эффективную очистку и надежную дезинфекцию контактных линз. За счет матрицы HydraGlyde®, которая способствует длительному увлажнению, в линзах комфортно в течении всего дня. Не содержит консервантов! Подходит для чувствительных глаз!",
    title: "ReNu MPS, раствор (120мл)",
    category: "solute",
    price: 5090,
    oldPrice: 5550,
    isRecommended: false,
    isDiscounted: true,
    specificationsName: ["Производитель"],
    specificationsInfo: ["Alcon - Ciba Vision"],
  ),
  Product(
    options: {
      "Базовая кривизна": ['8.4', '8.8'],
      'Оптическая сила': [
        '+8',
        '+7.5',
        '+7',
        '+6.5',
        '+6',
        '+5.5',
        '+5',
        '+4.5',
        '+4',
        '+3.5',
        '+3',
        '+2.5',
        '+2',
        '+1.5',
        '+1',
        '+0.5',
        '-0.5',
        '-1',
        '-1.5',
        '-2',
        '-2.5',
        '-3',
        '-3.5',
        '-4',
        '-4.5',
        '-5',
        '-5.5',
        '-6',
        '-6.5',
        '-7',
        '-7.5',
        '-8'
      ],
    },
    count: 1,
    images: ["assets/images/product_3.png"],
    description:
        "AOSEPT® plus HydraGlyde® обеспечивает эффективную очистку и надежную дезинфекцию контактных линз. За счет матрицы HydraGlyde®, которая способствует длительному увлажнению, в линзах комфортно в течении всего дня. Не содержит консервантов! Подходит для чувствительных глаз!",
    title: "Acuvue 1-day TruEye, (90 шт.)",
    category: "lens",
    price: 5170,
    oldPrice: 5890,
    isRecommended: true,
    isDiscounted: true,
    specificationsName: ["Производитель"],
    specificationsInfo: ["Alcon - Ciba Vision"],
  ),
  Product(
    options: {
      "Базовая кривизна": ['8.4', '8.8'],
      'Оптическая сила': [
        '+8',
        '+7.5',
        '+7',
        '+6.5',
        '+6',
        '+5.5',
        '+5',
        '+4.5',
        '+4',
        '+3.5',
        '+3',
        '+2.5',
        '+2',
        '+1.5',
        '+1',
        '+0.5',
        '-0.5',
        '-1',
        '-1.5',
        '-2',
        '-2.5',
        '-3',
        '-3.5',
        '-4',
        '-4.5',
        '-5',
        '-5.5',
        '-6',
        '-6.5',
        '-7',
        '-7.5',
        '-8'
      ],
    },
    count: 0,
    images: ["assets/images/product_4.png"],
    description:
        "AOSEPT® plus HydraGlyde® обеспечивает эффективную очистку и надежную дезинфекцию контактных линз. За счет матрицы HydraGlyde®, которая способствует длительному увлажнению, в линзах комфортно в течении всего дня. Не содержит консервантов! Подходит для чувствительных глаз!",
    title: "Air Optix Aqua (3 шт.)",
    category: "lens",
    price: 980,
    oldPrice: 0,
    isRecommended: true,
    isDiscounted: false,
    specificationsName: ["Производитель"],
    specificationsInfo: ["Alcon - Ciba Vision"],
  ),
  Product(
    options: {
      "Базовая кривизна": ['8.4', '8.8'],
      'Оптическая сила': [
        '+8',
        '+7.5',
        '+7',
        '+6.5',
        '+6',
        '+5.5',
        '+5',
        '+4.5',
        '+4',
        '+3.5',
        '+3',
        '+2.5',
        '+2',
        '+1.5',
        '+1',
        '+0.5',
        '-0.5',
        '-1',
        '-1.5',
        '-2',
        '-2.5',
        '-3',
        '-3.5',
        '-4',
        '-4.5',
        '-5',
        '-5.5',
        '-6',
        '-6.5',
        '-7',
        '-7.5',
        '-8'
      ],
    },
    count: 11,
    images: ["assets/images/product_5.png"],
    description:
        "AOSEPT® plus HydraGlyde® обеспечивает эффективную очистку и надежную дезинфекцию контактных линз. За счет матрицы HydraGlyde®, которая способствует длительному увлажнению, в линзах комфортно в течении всего дня. Не содержит консервантов! Подходит для чувствительных глаз!",
    title: "Air Optix Plus HydraGlyde (6 шт.)",
    category: "lens",
    price: 2025,
    oldPrice: 0,
    isRecommended: true,
    isDiscounted: false,
    specificationsName: ["Производитель"],
    specificationsInfo: ["Alcon - Ciba Vision"],
  ),
  Product(
    count: 3,
    images: ["assets/images/product_6.png"],
    description:
        "AOSEPT® plus HydraGlyde® обеспечивает эффективную очистку и надежную дезинфекцию контактных линз. За счет матрицы HydraGlyde®, которая способствует длительному увлажнению, в линзах комфортно в течении всего дня. Не содержит консервантов! Подходит для чувствительных глаз!",
    title: "Biotrue, раствор (120мл)",
    category: "solute",
    price: 339,
    oldPrice: 500,
    isRecommended: false,
    isDiscounted: true,
    specificationsName: ["Производитель"],
    specificationsInfo: ["Alcon - Ciba Vision"],
  ),
];


class Options {
  String name;
  List<String> parameters;

  Options(this.name, this.parameters);

  @override
  String toString() {
    return '{ ${this.name}, ${this.parameters} }';
  }
}